---
title: "Lab 2 - Intro to Data"
author: "Your name"
date: "Date of lab session"
output: 
  html_document: 
    highlight: tango
    theme: spacelab
---

```{r setup, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

* * *

## Lab report

**Load data**
```{r load_data}
nycflights <- read_csv("data/nycflights.csv")
```

#### Exercise 1: 

```{r}
# enter your code for Exercise 1 here

```

#### Exercise 2:



```{r}
# enter your code for Exercise 2 here
```

#### Exercise 3:

```{r}
# enter your code for Exercise 3 here
```

#### Exercise 4:
```{r}
# enter your code for Exercise 4 here
```

#### Exercise 5:
```{r}
# enter your code for Exercise 5 here
```

#### Exercise 6:
```{r}
# enter your code for Exercise 6 here
```

* * *

### On your own:

#### Exercise 7:

```{r}
# enter your code for Exercise 7 here
```

#### Exercise 8:
```{r}
# enter your code for Exercise 8 here
```

#### Exercise 9:
```{r}
# enter your code for Exercise 9 here
```
