---
title: "Lab 3 - Intro to the Tidyverse and Functions"
author: "Your name"
date: "Date of lab session"
output: 
html_document: 
highlight: tango
theme: spacelab
---

```{r setup, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

* * *

## Lab report

**Load data**
```{r load_data}
wordbank <- read_csv("https://dyurovsky.github.io/85309/data/lab3/wordbank.csv")
```

#### Exercise 1: 

```{r exercise-1}
# enter your code for Exercise 1 here

```

#### Exercise 2:

```{r exercise-2}
# enter your code for Exercise 2 here
```

#### Exercise 3:

```{r exercise-3}
# enter your code for Exercise 3 here
```

#### Exercise 4:

```{r exercise-4}
# try printing this out to see what left_join did
wordbank_difficulty <- left_join(wordbank, word_difficulty, by = "word")

hardest_word <- function(child) {
  word_tibble <- wordbank_difficulty # %>%
  # enter your code for Exercise 4 here and uncomment the pipe above
  
  word_tibble %>%
    pull(word) %>%
    first() # get the first word if there are multiple
}
```

* * *

### More practice:

#### Exercise 5:

```{r exercise-5}
# enter your code for Exercise 5 here
```

#### Exercise 6:

```{r exercise-6}
# enter your code for Exercise 6 here
```

#### Exercise 7:

```{r exercise-7}
# enter your code for Exercise 7 here
```

