
---
title: "Lab 4 - Foundations for statistical inference - Sampling distributions"
author: "Your name"
date: "Date of lab session"
output: 
  html_document: 
    highlight: tango
    theme: spacelab
---

```{r setup, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

* * *

## Lab report

**Load data**
```{r load_data}
ames <- read_csv("https://dyurovsky.github.io/85309/data/lab4/ames.csv")
```

```{r set_seed}
set.seed(85309)
```

#### Exercise 1: 
```{r ex1}
# enter your code for Exercise 1 here
```

#### Exercise 2:
```{r ex2}
# enter your code for Exercise 2 here
```

#### Exercise 3:
```{r ex3}
# enter your code for Exercise 3 here
```

#### Exercise 4:
```{r ex4}
# enter your code for Exercise 4 here
```

#### Exercise 5:
```{r ex5}
# enter your code for Exercise 5 here
```

#### Exercise 6:

```{r ex6}
# enter your code for Exercise 6 here
```

### More Practice:

#### Exercise 7:

```{r ex7}
# enter your code for Exercise 7 here
```

#### Exercise 8:


```{r ex8}
# enter your code for Exercise 8 here
```

#### Exercise 9:

```{r ex9}
# enter your code for Exercise 9 here
```

#### Exercise 10:

```{r ex10}
# enter your code for Exercise 10 here
```
