
---
title: "Regression and ANOVA for Professor ratings"
output:
  html_notebook:
    toc: yes
editor_options: 
  chunk_output_type: inline
---


```{r}
library(tidyverse)
theme_set(theme_classic(base_size = 16))
```

Load in professor rating data
```{r load_data}
prof_data <- read_csv("https://raw.githubusercontent.com/dyurovsky/psyc201/master/data/demos/prof_data.csv") %>%
  select(-X1)

head(prof_data)
```

Scatter plot of beauty vs. professor evaluation
```{r plot}
ggplot(prof_data, aes(x = beauty, y = profevaluation)) + 
  geom_point()
```

Full model
```{r full_model}
prof_lm <- lm(profevaluation ~ beauty + gender + age + formal + lower + 
                native + minority + students + tenure, data = prof_data)

summary(prof_lm)
```

Stepwise regression
```{r stepwise}
lm_null <- lm(profevaluation ~ 1, data = prof_data)
summary(lm_null)

lm_all <- lm(profevaluation ~ ., data = prof_data)
summary(lm_all)

# Backwards stepwise using defaults
lm_step <- step(lm_all)
summary(lm_step)

# Forward stepwise starting from null model
lm_forward <- step(lm_null, scope = list(lower = lm_null, upper = lm_all), direction = "forward")
summary(lm_forward)

# Backward stepwise without defaults
lm_backward <- step(lm_all, scope = list(lower = lm_null, upper = lm_all), direction = "backward")
summary(lm_backward)
```

Doing anova in R
```{r anova}
tenure_anova <- aov(profevaluation ~ tenure, data = prof_data)

summary(tenure_anova)

group_means <- prof_data %>%
  select(profevaluation, tenure) %>%
  group_by(tenure) %>%
  summarise(mean = mean(profevaluation), n = n())
group_means

overall_mean <- prof_data %>%
  select(profevaluation) %>%
  summarise(mean = mean(profevaluation), n = n())

f_dist <- data_frame(value = seq(.01,10,.01),
                     density = df(seq(.01,10,.01), 2, 450))

ggplot(f_dist, aes(x = value, y = density)) + 
  geom_point(size = .5) +
  xlab("F value") + 
  ylab("Probability") + 
  geom_vline(aes(xintercept = 2.706), color = "darkred", size = 1)

```

Comparing anova and linear regression
```{r anova_vs_lm}
summary(aov(profevaluation ~ tenure, data = prof_data))

summary(lm(profevaluation ~ tenure, data = prof_data))
```